import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const allenoire = localFont({
  src: [
  
    {
      path: '../app/../../public/fonts/Allenoire-regular.woff2', // Path relative to this file
      weight: '400',
      style: 'normal',
    },
     ],
  variable: '--font-allenoire', 
  display: 'swap', 
});

const britiSans = localFont({
  src : [
    {
      path : '../app/../../public/fonts/BritiSans.woff2',
      weight: '400',
      style: 'normal',
    }
  ],
  variable : '--font-britiSans',
  display: 'swap'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="{allenoire.variable} {britiSans.variable}">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
